# Generated by Django 6.0 on 2026-01-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='description',
            new_name='history',
        ),
    ]
