# Generated by Django 6.0 on 2025-12-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='souure_link',
            new_name='source_link',
        ),
    ]
